### ISSUE TITLE
zwe start ended with error code 35840

### ISSUE THREAD

**Issue by ccc13481** [zowe/launcher#73]
Hi

Moving on with baby steps...

I now get a:
12023-03-23 10:57:41 <ZWELNCH:83952099> C009232 INFO ZWEL0021I Zowe Launcher starting
 2023-03-23 10:57:41 <ZWELNCH:83952099> C009232 INFO ZWEL0023I Zowe YAML config file is 'FILE(/YCPU/var/zowe/GS-zowe-2.5.0.yaml)'
 2023-03-23 10:57:41 <ZWELNCH:83952099> C009232 INFO ZWEL0024I HA_INSTANCE_ID is 'ææha_instance_idåå'
 2023-03-23 10:57:41 <ZWELNCH:83952099> C009232 INFO ZWEL0017I ROOT_DIR is '/usr/lpp/zowe/zowe-2.5.0'
 2023-03-23 10:57:41 <ZWELNCH:83952099> C009232 INFO ZWEL0069I Configuration is valid
 2023-03-23 10:57:41 <ZWELNCH:83952099> C009232 INFO ZWEL0058I WORKSPACE_DIR is '/tmp/zowe/workspace'
 2023-03-23 10:57:48 <ZWELS:50397513> C009232 INFO (zwe-internal-start-prepare:343) Zowe version: v2.5.0
 2023-03-23 10:57:49 <ZWELS:50397513> C009232 INFO (zwe-internal-start-prepare:344) build and hash: v2.x/masterÆ2474 (aa2cf8870a46228f517c91a6c4e82ef13587d52d)
   * Output:
     node: read_yaml 10: /Y/usr/lpp/zowe/zowe-2.5.0/bin/commands/internal/start/prepare/index.sh 356: .: zwecli_process_command 4: /usr/lpp/zowe/zowe-2.5.0/bin/zwe 96: FSUM7351 not found
 2023-03-23 10:57:50 <ZWELS:50397513> C009232 INFO (zwe-internal-start-prepare:360) starting Zowe instance ycpu with /YCPU/var/zowe/GS-zowe-2.5.0.yaml ...
 node: generate_instance_env_from_yaml_config 15: prepare_workspace_directory 37: /Y/usr/lpp/zowe/zowe-2.5.0/bin/commands/internal/start/prepare/index.sh 372: .: zwecli_process_command 4: /usr/lpp/zowe/zowe-2.5.0/bin/zwe 96: FSUM7351 not found
 2023-03-23 10:57:51 <ZWELS:50397513> C009232 ERROR (bin/libs/config.sh,generate_instance_env_from_yaml_config:19) ZWEL0140E: Failed to translate Zowe configuration (/YCPU/var/zowe/GS-zowe-2.5.0.yaml).
 2023-03-23 10:57:51 <ZWELNCH:83952099> C009232 WARN ZWEL0066W command '/usr/lpp/zowe/zowe-2.5.0/bin/zwe internal start prepare --config "/YCPU/var/zowe/GS-zowe-2.5.0.yaml" --ha-instance ææha_instance_idåå 2>&1' ended with code 35840
 2023-03-23 10:57:51 <ZWELNCH:83952099> C009232 ERROR ZWEL0030E failed to prepare Zowe instance

HA_INSTANCE_ID  is with national characters but should be ok - everything is from configuration.
And the configuration seems to validate ok.

Any way to come closer?

BR
Frank Allan Rasmussen
Danske Bank

**Comment by pavel-jares-bcm** [comment]
Hello Frank,

The HA_INSTANCE_ID value seems damaged for a wrong encoding. I assume there should be store value `{{ha_instance_id}}`. The second part of the errors basically says that it is not possible to parse `zowe.yaml` file (ie. index.sh 356 tried to read value `zowe.launchScript.logLevel`).

The instance id is taken from STC. Could you please verify your member with JCL if it is in proper encoding? The value should be stored on the first line (ie. `//ZWESLSTC  PROC RGN=0M,HAINST='{{ha_instance_id}}'`).

The `zowe.yaml` file should be stored in UTF-8. Could you please verify if the encoding is correct and if the validation of the schema is passing?

What encodings do you use as system one? The default usually is IBM-1047.

PS: I guess this issue is more related to repository https://github.com/zowe/zowe-install-packaging.

**Comment by ccc13481** [comment]
Hi

The output from the STC after execution:

3 XXZWESLSTC  PROC RGN=0M,HAINST='{{ha_instance_id}}'                                                            
  XX********************************************************************/                                        
  XX* This program and the accompanying materials are                  */                                        
  XX* made available under the terms of the                            */                                        
  XX* Eclipse Public License v2.0                                      */                                        
  XX* which accompanies this distribution, and is available at         */                                        
  XX* https://www.eclipse.org/legal/epl-v20.html                       */                                        
  XX*                                                                  */                                        
  XX* SPDX-License-Identifier: EPL-2.0                                 */                                        
  XX*                                                                  */                                        
  XX* Copyright Contributors to the Zowe Project.                      */                                        
  XX********************************************************************/                                        
  XX*                                                                  */                                        
  XX* ZOWE LAUNCHER PROCEDURE                                          */                                        
  XX*                                                                  */                                        
  XX* NOTE: this procedure is a template, you will need to modify      */                                        
  XX*       #zowe_yaml variable to point to your Zowe YAML config      */                                        
  XX*       file.                                                      */                                        
  XX*                                                                  */                                        
  XX* Check https://docs.zowe.org for more details.                    */                                        
  XX*                                                                  */                                        
  XX********************************************************************/                                        
4 XXZWELNCH  EXEC PGM=ZWELNCH,REGION=&RGN,TIME=NOLIMIT,                                                          
  XX PARM='ENVAR(_CEE_ENVFILE=DD:STDENV),POSIX(ON),HEAPPOOLS(OFF)/&HAINST                                        
  XX             '                                                                                               
  IEFC653I SUBSTITUTION JCL - PGM=ZWELNCH,REGION=0M,TIME=NOLIMIT,PARM='ENVAR(_CEE_ENVFILE=DD:STDENV),POSIX(ON),  
  HEAPPOOLS(OFF)/{{ha_instance_id}}'                                                                             

This output is looked on from a PC3270 with code page 1047.

Tried with yaml file tagged as UTF-8:

Pathname  . . : /YCPU/var/zowe/GS-zowe-2.5.0.yaml                    
                                                                     
General Data                                Mode Fields              
 File Type . . : File                        Permissions . : 755     
 File Size . . : 18651                       Set User ID . : NO      
 Links . . . . : 1                           Set Group ID  : NO      
 Inode . . . . : 863                         Sticky Bit  . : NO      
 File Format . : ----                                                
 Last Modified : 2023/03/23 15:09:35        Extended Attributes      
 Last Changed  : 2023/03/28 15:34:04         Shared AS . . : YES     
 Last Accessed : 2023/03/28 15:34:45         APF Auth  . . : NO      
 Created . . . : 2023/03/16 14:50:42         Pgm Control . : NO      
 CCSID . . . . : 1208                        Shared Lib  . : NO      
 Text Convert  : NO                                                  
                                            Audit                    
Owner                                        Auditor . . . : ---     
 File  . . . . : C009232(1112542)            User  . . . . : fff     
 Group . . . . : ODBDEF(1244578987)                                  
                                            Device Data              
                                             Device Number : 11E     
                                             Major Device  :         
                                             Minor Device  :         

Same error.

Tried to comment out zowe.launchScript.logLevel - no luck.

The zowe part of the yaml look like this:
zowe:                                                                         
  runtimeDirectory: "/usr/lpp/zowe/zowe-2.5.0"                                
                                                                              
  logDirectory: /tmp/zowe/logs                                                
                                                                              
  workspaceDirectory: /tmp/zowe/workspace                                     
                                                                              
  extensionDirectory: /var/zowe/extensions                                    
                                                                              
  useConfigmgr: false                                                         
  configmgr:                                                                  
    validation: "COMPONENT-COMPAT"                                            
                                                                              
  job:                                                                        
    name: ZWE1SV                                                              
    prefix: ZWE1                                                              
                                                                              
  rbacProfileIdentifier: "1"                                                  
                                                                              
  cookieIdentifier: "1"                                                       
                                                                              
  externalDomains:                                                            
    - zowegs.danskenet.net                                                    
                                                                              
  externalPort: 7009                                                          
                                                                              
  environments:                                                               
                                                                              
    ZWED_SSH_PORT: 22                                                         
    ZWED_TN3270_PORT: 23                                                      
                                                                              
  certificate:                                                                
    keystore:                                                                 
      type: PKCS12                                                            
      file: "/var/zowe/keystore/localhost/localhost.keystore.p12"             
      password: "password"                                                    
      alias: "localhost"                                                      
    truststore:                                                               
      type: PKCS12                                                            
      file: "/var/zowe/keystore/localhost/localhost.truststore.p12"           
      password: "password"                                                    
    pem:                                                                      
      key: "/var/zowe/keystore/localhost/localhost.key"                       
      certificate: "/var/zowe/keystore/localhost/localhost.cer"               
      certificateAuthorities: "/var/zowe/keystore/local_ca/local_ca.cer"      
                                                                              
  verifyCertificates: STRICT                                                  
                                                                              
BR
Frank Allan Rasmussen
Danske Bank

**Comment by ccc13481** [comment]
Hi

Fixed - I had misspelled the node directory.

I will check later why I did not get an error for that.

BR
Frank Allan Rasmussen
Danske Bank
